(branch_statement) @keyword.conditional
(call_statement) @function.call
(choice_statement) @keyword.conditional
(exit_statement) @keyword.return
(say_statement) @string
(flag_statement) @keyword.coroutine
(signal_statement) @function.call
(sound_statement) @function.call
(identifier) @variable.member
(speech) @string
(name) @variable.builtin
(choice) @string
(code) @function.call
(expression) @function.call
(number) @number
(comment) @comment @spell
(end) @variable.parameter
(exit) @variable.parameter
(string) @string
(bbcode) @operator
["|"] @operator
